name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/rsync

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: 'Login'
      uses: docker/login-action@v2
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
        cache-from: type=registry,ref=${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
        cache-to: type=inline
